yamlApplicationConfig:
  kafka:
    clusters:
      - name: yaml
        bootstrapServers:  my-release-kafka.kafka.svc.cluster.local:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false